/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(prs_timed_burst_source.h) */
/* BINDTOOL_HEADER_FILE_HASH(75bd9f498f0fb3488896dc2dc6b6c75a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ofdm_prs_ranging/prs_timed_burst_source.h>
// pydoc.h is automatically generated in the build directory
#include <prs_timed_burst_source_pydoc.h>

void bind_prs_timed_burst_source(py::module& m)
{

    using prs_timed_burst_source = ::gr::ofdm_prs_ranging::prs_timed_burst_source;


    py::class_<prs_timed_burst_source,
               gr::block,
               gr::basic_block,
               std::shared_ptr<prs_timed_burst_source>>(
        m, "prs_timed_burst_source", D(prs_timed_burst_source))

        .def(py::init(&prs_timed_burst_source::make),
             py::arg("samp_rate") = 1.0E+7,
             py::arg("fft_len") = 1024,
             py::arg("cp_len") = 128,
             py::arg("active_bins") = 1024,
             py::arg("prs_symbols") = 16,
             py::arg("preamble_len") = 128,
             py::arg("preamble_repeats") = 16,
             py::arg("coarse_sync_len") = 839,
             py::arg("zero_guard_len") = 1000,
             py::arg("tail_guard_len") = 1000,
             py::arg("tx_lead_time") = 0.5,
             py::arg("burst_period") = 0.10000000000000001,
             py::arg("tx_amp") = 0.600000024F,
             py::arg("seed") = 13990001,
             py::arg("pings_per_trigger") = 1,
             py::arg("attach_tx_time") = true,
             py::arg("coarse_zc_root") = 25,
             D(prs_timed_burst_source, make))


        .def("frame_len",
             &prs_timed_burst_source::frame_len,
             D(prs_timed_burst_source, frame_len))


        .def("prs_start",
             &prs_timed_burst_source::prs_start,
             D(prs_timed_burst_source, prs_start))


        .def("prs_len",
             &prs_timed_burst_source::prs_len,
             D(prs_timed_burst_source, prs_len))


        .def("frame_samples",
             &prs_timed_burst_source::frame_samples,
             D(prs_timed_burst_source, frame_samples))

        ;
}
