#!/usr/bin/env python3
"""Generate the runtime Gold127 C++ table from the authoritative CSV."""

import argparse
import csv
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    with args.input.open(newline="", encoding="ascii") as source:
        rows = [[int(value) for value in row] for row in csv.reader(source)]

    if len(rows) != 129 or any(len(row) != 127 for row in rows):
        raise ValueError("Gold table must contain exactly 129 rows x 127 columns")
    if any(value not in (-1, 1) for row in rows for value in row):
        raise ValueError("Gold table values must be exactly -1 or +1")

    lines = [
        "/* Generated by tools/generate_gold127_header.py. Do not edit. */",
        "#ifndef INCLUDED_OFDM_PRS_RANGING_GOLD127_CODES_H",
        "#define INCLUDED_OFDM_PRS_RANGING_GOLD127_CODES_H",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace gr {",
        "namespace ofdm_prs_ranging {",
        "",
        "constexpr int gold127_family_size = 129;",
        "constexpr int gold127_code_length = 127;",
        "using gold127_code = std::array<int8_t, gold127_code_length>;",
        "using gold127_family = std::array<gold127_code, gold127_family_size>;",
        "",
        "constexpr gold127_family gold127_codes = {{",
    ]
    for row in rows:
        values = ", ".join(str(value) for value in row)
        lines.append(f"    gold127_code{{{{ {values} }}}},")
    lines.extend(
        [
            "}};",
            "",
            "} // namespace ofdm_prs_ranging",
            "} // namespace gr",
            "",
            "#endif /* INCLUDED_OFDM_PRS_RANGING_GOLD127_CODES_H */",
            "",
        ]
    )
    args.output.write_text("\n".join(lines), encoding="ascii")


if __name__ == "__main__":
    main()
